// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteTodo(ctx context.Context, id pgtype.UUID) error
	GetTodo(ctx context.Context, id pgtype.UUID) (Todo, error)
	ListTodos(ctx context.Context) ([]Todo, error)
	ListTodosByStatus(ctx context.Context, completed bool) ([]Todo, error)
	ToggleTodoComplete(ctx context.Context, id pgtype.UUID) (Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
