database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: todoapp
  ssl_mode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  database: 0

server:
  host: 0.0.0.0
  port: 4000

worker:
  enabled: true
  concurrency: 10

logger:
  level: info
  format: text